name: Release
on:
  push:
    tags:
      - v*
env:
  CI: true

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Publish to npm
        uses: laserware/propellant@v1.0.2
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
